[package]
name = "portfolio"
version = "0.1.0"
authors = ["VojtÄ›ch Jungmann", "Sebastian Pravda"]
edition = "2021"
publish = false

[workspace]
members = [".", "api", "core", "entity", "migration"]

[dependencies]
portfolio-api = { path = "api" }
